import type { Metadata } from "next"

import { sans } from "@/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Frontend Mentor | QR Code Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} bg-light-gray flex min-h-screen flex-col items-center justify-center px-[28px]`}
      >
        {children}
        <footer className="text-neutral-dark-grayish-blue text-grayish-blue mt-6 text-center text-sm">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            className="text-dark-blue underline"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a
            href="https://github.com/mauLovera"
            className="text-dark-blue underline"
          >
            Mauricio Lovera
          </a>
          .
        </footer>
      </body>
    </html>
  )
}
